### ISSUE TITLE
symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by eazzyLEE** [pusher/pusher-websocket-react-native#106]
Hello there! I am unable to run an iOS build successfully after installing and running `pod install`. I keep getting this error
ld: symbol(s) not found for architecture arm64.

![image](https://github.com/pusher/pusher-websocket-react-native/assets/29065790/97ecd6ae-b18f-48f9-9cbd-9f5a0d86c7ab)
![image](https://github.com/pusher/pusher-websocket-react-native/assets/29065790/539c860f-04a9-4caa-a4a4-9f7425e7eef1)

I have no clue where this is from.

**Comment by eazzyLEE** [comment]
this is on a M1 machine.
Xcode 14.1
I already had this `postinstall` in my Podfile:
config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"

**Comment by benjamin-tang-pusher** [comment]
Are you integrating Pusher Channels into an production app, or is the app still in development phase? If the latter, can you generate a new RN project, update your Ruby to a relatively new version (I use chruby and ruby-install instead of the system Ruby, which may be slightly old). Ensure your `ffi` gem is up to date (this library is crucial). Then try running pod install again.

**Comment by benw-pusher** [comment]
We haven't had a response here so closing out.
