### ISSUE TITLE
Why so different from the JS API?

### ISSUE THREAD

**Issue by fabiendeborde** [pusher/pusher-websocket-react-native#127]
Hello, I had to update an old project, and found out that the previous `pusher-js/react-native` was not working anymore, and this library was recommended instead.
I spent a few hours trying to refactor my pusher wrapper and I have to say that it is quite a pain.
It feels like the documentation is not ready yet, and the API is a lot different than the previous one (like totally different API).

Was there a particular reason for these breaking changes ?
I must admit I don't do much projects using React Native, so i have no idea if this is due to RN updates or the Pusher team wanted a new direction for this library.

I am going to check if I can replace Pusher with FCM and silent pushes since I need some realtime features, but I don't really need the payloads to be huge.

I didn't come here to blame anyone or just rant, but to give some feedback from a casual RN developer (and quite frequent Web developer).
I hope you can improve the documentation (and maybe the API) so that I can keep using this library in the future.

**Comment by benw-pusher** [comment]
Thanks for your feedback @fabiendeborde . We wanted to create a dedicate RN library rather than simply port the JS library, so breaking changes were going to be an unfortunate effect of these. There is still outstanding work for this library to fully realize our vision and so we advise you 'watch' this repository so you can be notified of future changes.
