### ISSUE TITLE
React Native Web support

### ISSUE THREAD

**Issue by swaaj** [pusher/pusher-websocket-react-native#64]
The package works well on Android and iOS platforms.
However, it doesn't seem to work on Web... Do you have a solution for working with pusher on React Native Web project ?

**Comment by benw-pusher** [comment]
at this time there are no plans to add support for React Native Web. For web implementations we recommend our [pusher-js library.](https://github.com/pusher/pusher-js)

**Comment by GustavoBonfimS** [comment]
Due to the growing movement towards creating universal apps (ios, android and web) it would be interesting to think about web support. This library is amazing, it would be great to be able to use the same library to create websites.

I will try to implement using specific files for each platform (index.ts and index.web.ts) using the web library. Hope it works.
