### ISSUE TITLE
receive notifications when app is closed or in background

### ISSUE THREAD

**Issue by iamhaaamed** [pusher/pusher-websocket-react-native#99]
I received notifications only when app is in foreground but not in closed or background state. How can we receive notifications when app is closed or in background?

**Comment by Kaue-Romero** [comment]
Hi @iamhaaamed 
I am using React-Native 0.71.4 and I still receiving the notifications in PRIVATE-channels with the app in background. I don´t know if the notification is on PRESENCE-channel but here it is normal
I am using the lib AppState from React-Native to follow the state of the the app 
https://reactnative.dev/docs/appstate
![image](https://github.com/pusher/pusher-websocket-react-native/assets/69368947/141f5102-9eb6-4fad-a428-4b2a5a5df9ab)

**Comment by fbenevides** [comment]
@iamhaaamed, assuming you're using Pusher Channels and not Beams, you should receive events while the app is in the background but not when it's closed because you need to be connected to Pusher to trigger/receive events.

About the background problem, can you please share more context, such as a piece of code or platform you're testing on? As @Kaue-Romero said previously, you should be receiving events normally.

**Comment by benjamin-tang-pusher** [comment]
Due to the lack of response, I will close this GH issue.
